services:
  mongodb:
    image: mongo:8
    container_name: lin-mongodb
    restart: unless-stopped
    ports:
      - "20010:20010"
    command: mongod --port 20010
    environment:
      MONGO_INITDB_DATABASE: lin_framework
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:8-alpine
    container_name: lin-redis
    restart: unless-stopped
    ports:
      - "20020:20020"
    command: redis-server --appendonly yes --port 20020
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
