services:
  mongodb:
    image: mongo:8
    container_name: lin-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lin_framework
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:8-alpine
    container_name: lin-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
