/**
 * 图标注册表
 *
 * 集中管理所有可用图标，供 IconSelector（菜单管理图标选择器）
 * 和 SidebarMenu（侧边栏渲染）共用，确保两侧图标一致。
 *
 * 使用方式：
 * ```ts
 * import { ICON_MAP } from '@/constants/icons';
 * const IconComponent = ICON_MAP['home']; // → HomeOutline
 * ```
 */
import type { Component } from 'vue';
import {
  AddOutline,
  AppsOutline,
  BarChartOutline,
  BasketOutline,
  BookOutline,
  BulbOutline,
  BusinessOutline,
  CafeOutline,
  CalendarOutline,
  CameraOutline,
  CardOutline,
  ChatboxEllipsesOutline,
  CloudOutline,
  CloudUploadOutline,
  CodeSlashOutline,
  ColorPaletteOutline,
  CompassOutline,
  ConstructOutline,
  CopyOutline,
  CubeOutline,
  DesktopOutline,
  DocumentTextOutline,
  DownloadOutline,
  EyeOutline,
  FileTrayOutline,
  FilterOutline,
  FlagOutline,
  FolderOutline,
  GameControllerOutline,
  GitBranchOutline,
  GridOutline,
  HammerOutline,
  HeartOutline,
  HomeOutline,
  ImageOutline,
  KeyOutline,
  LaptopOutline,
  LayersOutline,
  LibraryOutline,
  LinkOutline,
  LocationOutline,
  LockClosedOutline,
  MailOutline,
  MapOutline,
  MenuOutline,
  MusicalNotesOutline,
  NewspaperOutline,
  NotificationsOutline,
  PencilOutline,
  PeopleOutline,
  PersonOutline,
  PhonePortraitOutline,
  PieChartOutline,
  PrintOutline,
  RefreshOutline,
  SchoolOutline,
  SearchOutline,
  ServerOutline,
  SettingsOutline,
  ShareOutline,
  ShieldCheckmarkOutline,
  SpeedometerOutline,
  StarOutline,
  StorefrontOutline,
  TabletPortraitOutline,
  TerminalOutline,
  TimeOutline,
  TrendingUpOutline,
  TrashOutline,
  TvOutline,
  VideocamOutline,
  WalletOutline,
} from '@vicons/ionicons5';

/** 图标条目 */
export interface IconItem {
  name: string;
  label: string;
  component: Component;
}

/**
 * 图标名 → 组件 映射表
 *
 * 侧边栏通过此映射将后端返回的 icon 字段渲染为实际图标。
 */
export const ICON_MAP: Record<string, Component> = {
  dashboard: GridOutline,
  console: SpeedometerOutline,
  workbench: ConstructOutline,
  analysis: BarChartOutline,
  menu: MenuOutline,
  user: PersonOutline,
  role: ShieldCheckmarkOutline,
  permission: KeyOutline,
  file: FolderOutline,
  home: HomeOutline,
  settings: SettingsOutline,
  apps: AppsOutline,
  document: DocumentTextOutline,
  'file-tray': FileTrayOutline,
  people: PeopleOutline,
  lock: LockClosedOutline,
  bulb: BulbOutline,
  chat: ChatboxEllipsesOutline,
  news: NewspaperOutline,
  'bar-chart': BarChartOutline,
  'pie-chart': PieChartOutline,
  trending: TrendingUpOutline,
  calendar: CalendarOutline,
  mail: MailOutline,
  notification: NotificationsOutline,
  cloud: CloudOutline,
  server: ServerOutline,
  code: CodeSlashOutline,
  tools: HammerOutline,
  layers: LayersOutline,
  link: LinkOutline,
  map: MapOutline,
  flag: FlagOutline,
  star: StarOutline,
  heart: HeartOutline,
  book: BookOutline,
  pencil: PencilOutline,
  trash: TrashOutline,
  add: AddOutline,
  search: SearchOutline,
  filter: FilterOutline,
  download: DownloadOutline,
  upload: CloudUploadOutline,
  refresh: RefreshOutline,
  share: ShareOutline,
  copy: CopyOutline,
  print: PrintOutline,
  camera: CameraOutline,
  image: ImageOutline,
  video: VideocamOutline,
  music: MusicalNotesOutline,
  palette: ColorPaletteOutline,
  construct: ConstructOutline,
  git: GitBranchOutline,
  terminal: TerminalOutline,
  cube: CubeOutline,
  basket: BasketOutline,
  card: CardOutline,
  wallet: WalletOutline,
  time: TimeOutline,
  location: LocationOutline,
  compass: CompassOutline,
  business: BusinessOutline,
  school: SchoolOutline,
  library: LibraryOutline,
  store: StorefrontOutline,
  cafe: CafeOutline,
  game: GameControllerOutline,
  tv: TvOutline,
  phone: PhonePortraitOutline,
  tablet: TabletPortraitOutline,
  laptop: LaptopOutline,
  desktop: DesktopOutline,
  eye: EyeOutline,
};

/**
 * 图标列表（带中文标签），供 IconSelector 渲染选择面板。
 *
 * 常用图标排在最前。
 */
export const ICON_LIST: IconItem[] = [
  { name: 'dashboard', label: '仪表盘', component: GridOutline },
  { name: 'menu', label: '菜单', component: MenuOutline },
  { name: 'user', label: '用户', component: PersonOutline },
  { name: 'role', label: '角色', component: ShieldCheckmarkOutline },
  { name: 'permission', label: '权限', component: KeyOutline },
  { name: 'file', label: '文件', component: FolderOutline },
  { name: 'home', label: '首页', component: HomeOutline },
  { name: 'settings', label: '设置', component: SettingsOutline },
  { name: 'apps', label: '应用', component: AppsOutline },
  { name: 'document', label: '文档', component: DocumentTextOutline },
  { name: 'file-tray', label: '文件盘', component: FileTrayOutline },
  { name: 'people', label: '人群', component: PeopleOutline },
  { name: 'lock', label: '锁定', component: LockClosedOutline },
  { name: 'bulb', label: '灯泡', component: BulbOutline },
  { name: 'chat', label: '聊天', component: ChatboxEllipsesOutline },
  { name: 'news', label: '新闻', component: NewspaperOutline },
  { name: 'bar-chart', label: '柱状图', component: BarChartOutline },
  { name: 'pie-chart', label: '饼图', component: PieChartOutline },
  { name: 'trending', label: '趋势', component: TrendingUpOutline },
  { name: 'calendar', label: '日历', component: CalendarOutline },
  { name: 'mail', label: '邮件', component: MailOutline },
  { name: 'notification', label: '通知', component: NotificationsOutline },
  { name: 'cloud', label: '云', component: CloudOutline },
  { name: 'server', label: '服务器', component: ServerOutline },
  { name: 'code', label: '代码', component: CodeSlashOutline },
  { name: 'tools', label: '工具', component: HammerOutline },
  { name: 'layers', label: '层级', component: LayersOutline },
  { name: 'link', label: '链接', component: LinkOutline },
  { name: 'map', label: '地图', component: MapOutline },
  { name: 'flag', label: '旗帜', component: FlagOutline },
  { name: 'star', label: '星标', component: StarOutline },
  { name: 'heart', label: '收藏', component: HeartOutline },
  { name: 'book', label: '书籍', component: BookOutline },
  { name: 'pencil', label: '编辑', component: PencilOutline },
  { name: 'trash', label: '删除', component: TrashOutline },
  { name: 'add', label: '新增', component: AddOutline },
  { name: 'search', label: '搜索', component: SearchOutline },
  { name: 'filter', label: '筛选', component: FilterOutline },
  { name: 'download', label: '下载', component: DownloadOutline },
  { name: 'upload', label: '上传', component: CloudUploadOutline },
  { name: 'refresh', label: '刷新', component: RefreshOutline },
  { name: 'share', label: '分享', component: ShareOutline },
  { name: 'copy', label: '复制', component: CopyOutline },
  { name: 'print', label: '打印', component: PrintOutline },
  { name: 'camera', label: '相机', component: CameraOutline },
  { name: 'image', label: '图片', component: ImageOutline },
  { name: 'video', label: '视频', component: VideocamOutline },
  { name: 'music', label: '音乐', component: MusicalNotesOutline },
  { name: 'palette', label: '调色板', component: ColorPaletteOutline },
  { name: 'construct', label: '构建', component: ConstructOutline },
  { name: 'git', label: 'Git', component: GitBranchOutline },
  { name: 'terminal', label: '终端', component: TerminalOutline },
  { name: 'cube', label: '立方体', component: CubeOutline },
  { name: 'basket', label: '购物篮', component: BasketOutline },
  { name: 'card', label: '卡片', component: CardOutline },
  { name: 'wallet', label: '钱包', component: WalletOutline },
  { name: 'time', label: '时间', component: TimeOutline },
  { name: 'location', label: '位置', component: LocationOutline },
  { name: 'compass', label: '指南针', component: CompassOutline },
  { name: 'business', label: '企业', component: BusinessOutline },
  { name: 'school', label: '学校', component: SchoolOutline },
  { name: 'library', label: '图书馆', component: LibraryOutline },
  { name: 'store', label: '商店', component: StorefrontOutline },
  { name: 'cafe', label: '咖啡', component: CafeOutline },
  { name: 'game', label: '游戏', component: GameControllerOutline },
  { name: 'tv', label: '电视', component: TvOutline },
  { name: 'phone', label: '手机', component: PhonePortraitOutline },
  { name: 'tablet', label: '平板', component: TabletPortraitOutline },
  { name: 'laptop', label: '笔记本', component: LaptopOutline },
  { name: 'desktop', label: '桌面', component: DesktopOutline },
  { name: 'eye', label: '眼睛', component: EyeOutline },
];
